# get all courses
GET http://localhost:3000/api/v1/courses HTTP/1.1
###

# get courses by bootcamps
GET http://localhost:3000/api/v1/bootcamps/:bootcampId/courses HTTP/1.1
###

# get a single course
GET http://localhost:3000/api/v1/courses/5d725a4a7b292f5f8ceff789 HTTP/1.1
###

# create a course
POST http://localhost:3000/api/v1/bootcamps/5d725a1b7b292f5f8ceff788/courses HTTP/1.1
Content-Type:  application/json

{
  	"title": "Front End Web Development 2",
		"description": "This course will provide you with all of the essentials to become a successful frontend web developer. You will learn to master HTML, CSS and front end JavaScript, along with tools like Git, VSCode and front end frameworks like Vue",
		"weeks": 8,
		"tuition": 14500,
		"minimumSkill": "beginner",
		"scholarhipsAvailable": true
}
###

# update a course
PUT http://localhost:3000/api/v1/courses/5d725c84c4ded7bcb480eaa0 HTTP/1.1
Content-Type:  application/json

{
  "tuition": 13000,
  "minimumSkill": "beginner"
}
###

# delete a course
DELETE http://localhost:3000/api/v1/courses/5d725c84c4ded7bcb480eaa0 HTTP/1.1
###