// export const ADD_IMAGE = 'ADD_IMAGE';
// export const ADD_IMAGE_REQUEST = 'ADD_IMAGE_REQUEST';
// export const IMAGE_ERROR = 'IMAGE_ERROR';
export const GET_BOOTCAMP = 'GET_BOOTCAMP';
export const GET_BOOTCAMP_REQUEST = 'GET_BOOTCAMP_REQUEST';
export const GET_BOOTCAMP_ERROR = 'GET_BOOTCAMP_ERROR';
export const GET_SINGLE_BOOTCAMP = 'GET_SINGLE_BOOTCAMP';
export const GET_SINGLE_BOOTCAMP_ERROR = 'GET_SINGLE_BOOTCAMP_ERROR';
export const GET_SINGLE_BOOTCAMP_REQUEST = 'GET_SINGLE_BOOTCAMP_REQUEST';
export const GET_SINGLE_BOOTCAMP_COURSE_REQUEST =
  'GET_SINGLE_BOOTCAMP_COURSE_REQUEST';
export const GET_SINGLE_BOOTCAMP_COURSE = 'GET_SINGLE_BOOTCAMP_COURSE';
export const GET_SINGLE_BOOTCAMP_COURSE_ERROR =
  'GET_SINGLE_BOOTCAMP_COURSE_ERROR';
export const GET_SINGLE_BOOTCAMP_REVIEW_REQUEST =
  'GET_SINGLE_BOOTCAMP_REVIEW_REQUEST';
export const GET_SINGLE_BOOTCAMP_REVIEW = 'GET_SINGLE_BOOTCAMP_REVIEW';
export const GET_SINGLE_BOOTCAMP_REVIEW_ERROR =
  'GET_SINGLE_BOOTCAMP_REVIEW_ERROR';
export const CREATE_BOOTCAMP_REQUEST = ' CREATE_BOOTCAMP_REQUEST';
export const CREATE_BOOTCAMP_SUCCESS = ' CREATE_BOOTCAMP_SUCCESS';
export const CREATE_BOOTCAMP_ERROR = ' CREATE_BOOTCAMP_ERROR';
