export const GET_COURSE = 'GET_COURSE';
export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST';
export const GET_COURSE_ERROR = 'GET_COURSE_ERROR';
export const GET_SINGLE_COURSE = 'GET_SINGLE_COURSE';
export const GET_SINGLE_COURSE_REQUEST = 'GET_SINGLE_COURSE_REQUEST';
export const GET_SINGLE_COURSE_ERROR = 'GET_SINGLE_COURSE_ERROR';
