export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST';
export const GET_REVIEWS_ERROR = 'GET_REVIEWS_ERROR';
export const GET_SINGLE_REVIEW_SUCCESS = 'GET_SINGLE_REVIEW_SUCCESS';
export const GET_SINGLE_REVIEW_REQUEST = 'GET_SINGLE_REVIEW_REQUEST';
export const GET_SINGLE_REVIEW_ERROR = 'GET_SINGLE_REVIEW_ERROR';
